### ISSUE TITLE
PDF without image

### ISSUE THREAD

**Issue by kja-xyt** [pmchlk/pdfgenerator#1]
First of all, thanks for a great example. But I'm struggling with the logo image not being visible.

It seems that it is already not visible in the Chrome browser. Please have a look at my code change and the result.

Do you have any idea how to fix it?

```
            await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
                ExecutablePath = PuppeteerExtensions.ExecutablePath
            });
```

![image](https://user-images.githubusercontent.com/16593018/121152191-46bca980-c845-11eb-9525-4f6747ea9689.png)

**Comment by pauljame** [comment]
Same problem here... Any fix ?

**Comment by rekosko** [comment]
I have the same issue. Any ideas?

**Comment by pmchlk** [comment]
Well, the problem is with the path under the .cshtml file in the img src

In the repo, under the src I am using the relative path to the image. To fix the problem, we need to provide an absolute path for the template service to generate the image.

In order to do that, just add address of the host in InvoiceTemplate.cshtml image src =>  `<img src="http://localhost:5000/images/logo.png" style="width:100%; max-width:150px;">`

There are many ways of how to always have a proper URL, you can add BaseViewModel and make InvoiceViewModel inherit it. Under BaseViewModel you can have Host property which is going to be set basing on the application configuration, then under every occurrence of the img src, you can simply set @Model.Host instead of hard-coded http://localhost:5000

You can also declare UrlConfiguration model, Configure It under startup and use dependency injection under the cshtml file, then you can simply read directly from the application configuration. More about options pattern in ASP.NET Core: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1
